const shipsCoords = [
    [
        { coordinate: "2m1", direction: "d", length: 1 },
        { coordinate: "1m4", direction: "d", length: 1 },
        { coordinate: "2m6", direction: "r", length: 3 },
        { coordinate: "4m0", direction: "r", length: 2 },
        { coordinate: "4m4", direction: "d", length: 4 },
        { coordinate: "5m8", direction: "d", length: 1 },
        { coordinate: "8m7", direction: "r", length: 1 },
        { coordinate: "9m1", direction: "d", length: 2 },
        { coordinate: "9m3", direction: "r", length: 3 },
        { coordinate: "10m7", direction: "r", length: 2 },
    ],
    [
        { coordinate: "1m2", direction: "r", length: 1 },
        { coordinate: "1m6", direction: "d", length: 1 },
        { coordinate: "2m8", direction: "r", length: 2 },
        { coordinate: "4m3", direction: "r", length: 3 },
        { coordinate: "5m8", direction: "d", length: 4 },
        { coordinate: "6m0", direction: "r", length: 1 },
        { coordinate: "8m2", direction: "r", length: 1 },
        { coordinate: "9m4", direction: "d", length: 2 },
        { coordinate: "10m6", direction: "r", length: 3 },
        { coordinate: "10m0", direction: "r", length: 2 },
    ],
    [
        { coordinate: "1m0", direction: "r", length: 4 },
        { coordinate: "3m3", direction: "d", length: 3 },
        { coordinate: "3m7", direction: "r", length: 2 },
        { coordinate: "4m5", direction: "d", length: 1 },
        { coordinate: "5m9", direction: "d", length: 1 },
        { coordinate: "7m0", direction: "r", length: 1 },
        { coordinate: "8m2", direction: "r", length: 2 },
        { coordinate: "6m7", direction: "d", length: 3 },
        { coordinate: "10m1", direction: "r", length: 2 },
        { coordinate: "10m7", direction: "r", length: 1 },
    ],
    [
        { coordinate: "1m1", direction: "r", length: 2 },
        { coordinate: "3m3", direction: "r", length: 3 },
        { coordinate: "5m0", direction: "r", length: 1 },
        { coordinate: "5m6", direction: "r", length: 2 },
        { coordinate: "7m8", direction: "d", length: 1 },
        { coordinate: "7m4", direction: "d", length: 4 },
        { coordinate: "9m7", direction: "r", length: 3 },
        { coordinate: "10m1", direction: "r", length: 2 },
        { coordinate: "8m1", direction: "r", length: 1 },
        { coordinate: "1m9", direction: "d", length: 1 },
    ],
    [
        { coordinate: "1m5", direction: "d", length: 4 },
        { coordinate: "1m3", direction: "d", length: 1 },
        { coordinate: "2m7", direction: "r", length: 3 },
        { coordinate: "6m4", direction: "d", length: 2 },
        { coordinate: "5m1", direction: "r", length: 1 },
        { coordinate: "7m7", direction: "d", length: 1 },
        { coordinate: "8m0", direction: "r", length: 1 },
        { coordinate: "9m2", direction: "d", length: 2 },
        { coordinate: "3m0", direction: "r", length: 3 },
        { coordinate: "10m5", direction: "r", length: 2 },
    ],
];

export default shipsCoords;
